version: "3.8"
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - api-server
  api-server:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    environment:
      - MONGODB_URL=mongodb+srv://businessdanith:dRAEIKZB7ZX8816O@cluster0.kq194bv.mongodb.net/Product_db?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local